<a href="https://colab.research.google.com/github/mariamarins-prog/Ciencias_dados/blob/main/Aula2_DataScience_MKT_MariaMarins_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 2 - 16/09 Manipulação de Dados

In [6]:
import pandas as pd

In [4]:
import pandas as pd

cidades = pd.DataFrame(
[
  ['Paraná', 'Londrina', 575377, 1356.00],
  ['São Paulo', 'São Carlos', 254484, 1508.00],
  ['Santa Catarina', 'Florianópolis', 508826, 1798.00],
  ['Paraná', 'Curitiba', 1963726, 2293.00],
  ['São Paulo', 'Campinas', 1223237, 1710.00]
], columns=['Estado', 'Cidade', 'Habitantes', 'Salário-Médio'])
cidades

           Estado         Cidade  Habitantes  Salário-Médio
0          Paraná       Londrina      575377         1356.0
1       São Paulo     São Carlos      254484         1508.0
2  Santa Catarina  Florianópolis      508826         1798.0
3          Paraná       Curitiba     1963726         2293.0
4       São Paulo       Campinas     1223237         1710.0

In [8]:
import pandas as pd

df=pd.read_csv("qualidade_vinho.csv", sep= ",", header=0)
df.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'qualidade_vinho.csv'

In [9]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0

In [10]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

      Estado      Cidade  Habitantes  Salário-Médio
0     Paraná    Londrina      575377         1356.0
1  São Paulo  São Carlos      254484         1508.0